---
driver:
  name: ec2
  tags:
     Environment: development
  
transport:
  username: ubuntu
  
provisioner:
  name: chef_solo
  always_update_cookbooks: <%= !ENV['CI'] %>

verifier:
  name: inspec

platforms:
 - name: ubuntu-14.04
 - name: ubuntu-16.04
 - name: ubuntu-18.04

suites:
  - name: default
    run_list:
      - recipe[logentries_agent::default]
    attributes:
      le:
        pull-server-side-config: false
